workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Locate and Install CocoaPods
        script: |
          # Buscamos dónde está el Podfile
          if [ -f "ios/Podfile" ]; then
            cd ios
            pod install
          else
            echo "Podfile no encontrado en ios/. Intentando regenerar..."
            flutter create .
            cd ios
            pod install
          fi
      - name: Flutter build ios
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa